# Generated by Django 5.0.6 on 2024-07-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ('description',)},
        ),
    ]
