# Generated by Django 5.0.6 on 2024-07-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_transactions_id_alter_transactions_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
