# Generated by Django 5.0.6 on 2024-07-26 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transactions_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='id',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
